# Generated by Django 5.0 on 2023-12-17 14:33

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('introduction_title', models.CharField(max_length=255)),
                ('introduction_content', ckeditor.fields.RichTextField()),
                ('introduction_small_image', models.ImageField(upload_to='about_us/introduction_small_images/', verbose_name='introduction_small_image')),
                ('introduction_big_image', models.ImageField(upload_to='about_us/introduction_big_images/', verbose_name='introduction_big_image')),
                ('team_title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllProjectPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('show_booking_section', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='appointment/', verbose_name='appointment_image')),
                ('sub_title', models.TextField(default='Afspraak maken')),
                ('description', models.TextField(default='We komen langs met vrijblijvend advies.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalculatedBlockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('sub_title_two', models.TextField()),
                ('description', models.TextField()),
                ('description_two', models.TextField()),
                ('new_construction_text', models.TextField()),
                ('renovation_text', models.TextField()),
                ('image', models.ImageField(upload_to='calculate_block/', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactFeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=25, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('address_title', models.CharField(max_length=255)),
                ('address_link', models.URLField(max_length=250)),
                ('link_title', models.CharField(default='Algemene voorwaarden', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('introduction_left_title', models.TextField()),
                ('introduction_left_sub_title', models.CharField(max_length=255)),
                ('introduction_left_content', ckeditor.fields.RichTextField(verbose_name='Introduction Left Content')),
                ('introduction_right_sub_title', models.TextField()),
                ('introduction_right_header_title', models.TextField()),
                ('introduction_right_content', ckeditor.fields.RichTextField(verbose_name='Introduction Right Content')),
                ('show_booking_section', models.BooleanField(default=True)),
                ('overview_title', models.TextField()),
                ('overview_sub_title', models.TextField()),
                ('completed_projects_block_title', models.TextField()),
                ('completed_projects_block_sub_title', models.TextField()),
                ('completed_projects_block_description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MakeAppointmentPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('introduction_title', models.TextField()),
                ('introduction_sub_title', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetadataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremiumLoansPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.URLField(max_length=255)),
                ('renovation_title', models.TextField(null=True)),
                ('renovation_sub_title', models.TextField(null=True)),
                ('renovation_block', ckeditor.fields.RichTextField(verbose_name='Renovation Block')),
                ('renovation_premium_title', models.TextField(null=True)),
                ('renovation_premium_sub_title', models.TextField(null=True)),
                ('renovation_premium_image', models.ImageField(null=True, upload_to='premium_loans_page/', verbose_name='personal situation image')),
                ('renovation_premium_block', ckeditor.fields.RichTextField(verbose_name='Renovation Premium Block')),
                ('get_premium_block_left_title', models.TextField(null=True)),
                ('get_premium_block_left_sub_title', models.TextField(null=True)),
                ('get_premium_block_left', ckeditor.fields.RichTextField(verbose_name='Get Premium Block Left')),
                ('get_premium_block_right_title', models.TextField(null=True)),
                ('get_premium_block_right', ckeditor.fields.RichTextField(verbose_name='Get Premium Block Right')),
                ('personal_situation_title', models.TextField(null=True)),
                ('personal_situation_sub_title', models.TextField(null=True)),
                ('personal_situation_block', ckeditor.fields.RichTextField(verbose_name='Personal Situation Block')),
                ('personal_situation_image', models.ImageField(upload_to='premium_loans_page/', verbose_name='personal situation image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('head_title', models.TextField(default='Privacy policy')),
                ('title', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewsStarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_reviews', models.IntegerField()),
                ('title', models.TextField(blank=True)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutUsImageSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_body', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='sliders/banner_fills/', verbose_name='banner_fill')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='website.aboutuspagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutUsHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='about_us/histories/', verbose_name='about_us_history')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='website.aboutuspagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutUsTeamMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='about_us/team_members/', verbose_name='about_us_team_member')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='website.aboutuspagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllProjectCalculatorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='calculate_block/', verbose_name='image')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_block', to='website.allprojectpagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllProjectSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_body', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='sliders/banner_fills/', verbose_name='banner_fill')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='website.allprojectpagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('introduction_left_title', models.TextField()),
                ('introduction_left_sub_title', models.CharField(max_length=255)),
                ('introduction_left_content', ckeditor.fields.RichTextField(verbose_name='Introduction Left Content')),
                ('introduction_right_sub_title', models.TextField()),
                ('introduction_right_header_title', models.TextField()),
                ('introduction_right_content', ckeditor.fields.RichTextField(verbose_name='Introduction Right Content')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('related_projects_block_title', models.TextField(blank=True, null=True)),
                ('related_projects_block_sub_title', models.TextField(blank=True, null=True)),
                ('completed_projects_block_title', models.TextField(blank=True, null=True)),
                ('completed_projects_block_sub_title', models.TextField(blank=True, null=True)),
                ('completed_projects_block_description', models.TextField(blank=True, null=True)),
                ('show_booking_section', models.BooleanField(default=False)),
                ('index_preview_icon', models.ImageField(upload_to='index_preview_icons/', verbose_name='index_preview_icon')),
                ('index_preview_text', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalculatorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='calculate_block/', verbose_name='image')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_block', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnimationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animation_type', models.CharField(choices=[('crepi', 'crepi'), ('dakwerken', 'dakwerken'), ('ramen_deuren', 'ramen_deuren'), ('gevelisolatie', 'gevelisolatie')], default='crepi', max_length=30)),
                ('animation_turn', models.BooleanField(default=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animation_block', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategorySliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_body', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='sliders/banner_fills/', verbose_name='banner_fill')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactImageSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_body', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='sliders/banner_fills/', verbose_name='banner_fill')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='website.contactpagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddressParagraphModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paragraph', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_paragraphs', to='website.contactpagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content Block Content')),
                ('image', models.ImageField(upload_to='content_block/before/', verbose_name='image')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_block', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CTAOptionalBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('content', ckeditor.fields.RichTextField(verbose_name='Description Block Content')),
                ('image', models.ImageField(upload_to='description_block/', verbose_name='image')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description_block', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexCalculatorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='calculate_block/', verbose_name='image')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_block', to='website.indexpagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_body', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='sliders/banner_fills/', verbose_name='banner_fill')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='website.indexpagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MakeAppointmentAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='website.makeappointmentpagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MakeAppointmentSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_body', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='sliders/banner_fills/', verbose_name='banner_fill')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='website.makeappointmentpagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremiumLoansSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_body', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='sliders/banner_fills/', verbose_name='banner_fill')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='website.premiumloanspagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicySubBlockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_blocks', to='website.privacypolicymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('content', models.TextField()),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_block', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='related_projects/', verbose_name='image')),
                ('path_to_page', models.CharField(blank=True, max_length=100, null=True)),
                ('button_text', models.CharField(default='Meer informatie', max_length=60)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_projects', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('image_before', models.ImageField(upload_to='result_block/before/', verbose_name='image_before')),
                ('image_after', models.ImageField(upload_to='result_block/after/', verbose_name='image_after')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_block', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.reviewsstarsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('post_code', models.CharField(max_length=30)),
                ('estimate_facade_area', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='feedbacks/', verbose_name='feedback')),
                ('appointments', models.ManyToManyField(blank=True, null=True, related_name='feedbacks', to='website.servicesappointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('gallery_title', models.TextField()),
                ('gallery_sub_title', models.TextField()),
                ('show_booking_section', models.BooleanField(default=True)),
                ('specifications_block_one_title', models.TextField()),
                ('specifications_block_tow_title', models.TextField()),
                ('related_categories', models.ManyToManyField(related_name='related_single_projects', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SinglePageResultBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('image_before', models.ImageField(upload_to='result_block/before/', verbose_name='image_before')),
                ('image_after', models.ImageField(upload_to='result_block/after/', verbose_name='image_after')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_block', to='website.singleprojectmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SinglePageCalculatorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='calculate_block/', verbose_name='image')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_block', to='website.singleprojectmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreviewItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='single_pages/preview_images/', verbose_name='image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_images', to='website.singleprojectmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='single_pages/images/', verbose_name='image')),
                ('video', models.FileField(blank=True, null=True, upload_to='single_pages/videos', verbose_name='Video')),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='single_pages/video_posters/', verbose_name='video_poster')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='website.singleprojectmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleProjectSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_body', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='sliders/banner_fills/', verbose_name='banner_fill')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='website.singleprojectmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificationsBlockOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications_block_one', to='website.singleprojectmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificationsBlockTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications_block_two', to='website.singleprojectmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('video', models.FileField(upload_to='video_block/', verbose_name='Video')),
                ('video_poster', models.ImageField(upload_to='video_poster/', verbose_name='video_poster')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_block', to='website.categorypage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
