# Generated by Django 5.0 on 2023-12-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspagemodel',
            name='introduction_title',
            field=models.TextField(),
        ),
    ]
