# Generated by Django 5.0 on 2023-12-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_aboutuspagemodel_introduction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutushistorymodel',
            name='title',
            field=models.TextField(),
        ),
    ]
