# Generated by Django 5.0 on 2023-12-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_aboutushistorymodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusimageslidermodel',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/banner_fills/', verbose_name='banner_fill'),
        ),
        migrations.AlterField(
            model_name='allprojectslidermodel',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/banner_fills/', verbose_name='banner_fill'),
        ),
        migrations.AlterField(
            model_name='categoryslidermodel',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/banner_fills/', verbose_name='banner_fill'),
        ),
        migrations.AlterField(
            model_name='contactimageslidermodel',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/banner_fills/', verbose_name='banner_fill'),
        ),
        migrations.AlterField(
            model_name='indexslidermodel',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/banner_fills/', verbose_name='banner_fill'),
        ),
        migrations.AlterField(
            model_name='makeappointmentslider',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/banner_fills/', verbose_name='banner_fill'),
        ),
        migrations.AlterField(
            model_name='premiumloansslidermodel',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/banner_fills/', verbose_name='banner_fill'),
        ),
        migrations.AlterField(
            model_name='singleprojectslidermodel',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/banner_fills/', verbose_name='banner_fill'),
        ),
    ]
