# Generated by Django 5.0 on 2023-12-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_aboutusimageslidermodel_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='introduction_left_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='introduction_left_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='introduction_left_sub_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indexpagemodel',
            name='introduction_left_sub_title',
            field=models.TextField(),
        ),
    ]
