# Generated by Django 5.0 on 2023-12-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_categorypage_introduction_left_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='index_preview_icon',
            field=models.ImageField(blank=True, null=True, upload_to='index_preview_icons/', verbose_name='index_preview_icon'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='index_preview_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
