# Generated by Django 5.0 on 2023-12-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_categorypage_index_preview_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='order_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='order_by',
            field=models.IntegerField(default=0),
        ),
    ]
