# Generated by Django 5.0 on 2023-12-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_categorypage_order_by_indexpagemodel_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='index_preview_icon',
            field=models.FileField(blank=True, null=True, upload_to='index_preview_icons/', verbose_name='index_preview_icon'),
        ),
    ]
