# Generated by Django 5.0 on 2023-12-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_categorypage_index_preview_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleprojectmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='singleprojectmodel',
            name='slug',
        ),
    ]
