# Generated by Django 5.0 on 2023-12-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_singleprojectmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypage',
            options={'ordering': ['order_by']},
        ),
        migrations.DeleteModel(
            name='DescriptionBlock',
        ),
    ]
