# Generated by Django 5.0 on 2023-12-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '1013_custom_migrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecificationsBlockTwo',
        ),
    ]
