# Generated by Django 5.0 on 2023-12-23 15:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '1014_delete_specificationsblocktwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('head_title', models.TextField(default='Privacy policy')),
                ('title', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('head_title', models.TextField(default='Privacy policy')),
                ('title', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CookieSubBlockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_blocks', to='website.cookiemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditionsSubBlockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_blocks', to='website.termsandconditionsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
