# Generated by Django 5.0 on 2023-12-23 15:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '1015_cookiemodel_termsandconditionsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta tittle')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('show_slider', models.BooleanField(default=False)),
                ('show_send_reviews_button', models.BooleanField(default=True)),
                ('introduction_left_title', models.TextField()),
                ('introduction_left_sub_title', models.TextField()),
                ('introduction_left_intro', models.TextField(blank=True, null=True)),
                ('introduction_left_content', ckeditor.fields.RichTextField(verbose_name='Introduction Left Content')),
                ('introduction_right_sub_title', models.TextField()),
                ('introduction_right_header_title', models.TextField()),
                ('introduction_right_content', ckeditor.fields.RichTextField(verbose_name='Introduction Right Content')),
                ('order_by', models.IntegerField(default=0)),
                ('jobs_header', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobsImageSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_body', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='sliders/banner_fills/', verbose_name='banner_fill')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='website.jobspagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='website.jobspagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
