# Generated by Django 5.0 on 2023-12-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '1016_jobspagemodel_jobsimageslidermodel_vacationmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationmodel',
            options={'ordering': ('order_by',)},
        ),
        migrations.AddField(
            model_name='vacationmodel',
            name='order_by',
            field=models.IntegerField(default=0),
        ),
    ]
