# Generated by Django 5.0 on 2023-12-23 16:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '1017_alter_vacationmodel_options_vacationmodel_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusimageslidermodel',
            name='slider_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutusimageslidermodel',
            name='slider_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='allprojectslidermodel',
            name='slider_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='allprojectslidermodel',
            name='slider_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='categoryslidermodel',
            name='slider_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='categoryslidermodel',
            name='slider_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactimageslidermodel',
            name='slider_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactimageslidermodel',
            name='slider_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indexslidermodel',
            name='slider_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indexslidermodel',
            name='slider_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobsimageslidermodel',
            name='slider_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobsimageslidermodel',
            name='slider_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobspagemodel',
            name='introduction_left_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Introduction Left Content'),
        ),
        migrations.AlterField(
            model_name='makeappointmentslider',
            name='slider_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='makeappointmentslider',
            name='slider_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='premiumloansslidermodel',
            name='slider_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='premiumloansslidermodel',
            name='slider_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='singleprojectslidermodel',
            name='slider_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='singleprojectslidermodel',
            name='slider_title',
            field=models.TextField(),
        ),
    ]
